# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 MainWindow.ui code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1280, 720)
        Login.setStyleSheet("QLineEdit{\n"
"    border:0px; margin:10px;\n"
"     margin-left:50px;\n"
"     margin-right:50px;\n"
"     border-bottom: 2px solid #B3B3B3;\n"
"     font-family: \"Microsoft Yahei\";\n"
"     font-size:    20px;\n"
"     font-wight: blod;\n"
"}\n"
"\n"
"QLineEdit:Focus{\n"
"    border-bottom: 3px soild  #E680BD\n"
"}"
"#Login{border-image:url(Background.png);}")
        self.label = QtWidgets.QLabel(parent=Login)
        self.label.setGeometry(QtCore.QRect(430, 220, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Login)
        self.label_2.setGeometry(QtCore.QRect(440, 340, 61, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=Login)
        self.lineEdit.setGeometry(QtCore.QRect(520, 210, 361, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Login)
        self.lineEdit_2.setGeometry(QtCore.QRect(520, 330, 361, 51))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=Login)
        self.pushButton.setGeometry(QtCore.QRect(300, 500, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Login)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 500, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Login)
        self.pushButton_3.setGeometry(QtCore.QRect(810, 500, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "基于ChatGPT的幼儿园信息管理系统"))
        self.label.setText(_translate("Login", "用户名："))
        self.label_2.setText(_translate("Login", "密码："))
        self.pushButton.setText(_translate("Login", "人脸识别"))
        self.pushButton_2.setText(_translate("Login", "登录"))
        self.pushButton_3.setText(_translate("Login", "取消"))
